import mongoose from "mongoose";

const rentalLoanSchema = new mongoose.Schema({
  // Loan Identification (auto-generated by pre-save hook)
  loanId: {
    type: String,
    unique: true,
    required: false, // Will be auto-generated by pre-save hook
    index: true
  },
  userId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
    index: true
  },
  contractId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'RentLockContract',
    required: true
  },

  // Loan Details
  loanType: {
    type: String,
    enum: ['security_deposit', 'first_month_rent', 'maintenance_charges'],
    required: true,
    index: true
  },
  loanAmount: {
    type: Number,
    required: true,
    min: 0
  },
  interestRate: {
    type: Number,
    required: true,
    min: 0,
    max: 100
  },
  tenure: {
    type: Number, // in months
    required: true,
    min: 1,
    max: 60
  },

  // Partner Information
  partnerName: {
    type: String, // NBFC/Bank name
    required: true
  },
  partnerLoanId: {
    type: String,
    default: null
  },
  partnerContact: {
    email: String,
    phone: String
  },

  // Status
  status: {
    type: String,
    enum: ['pending', 'approved', 'disbursed', 'rejected', 'repaid', 'defaulted'],
    default: 'pending',
    index: true
  },

  // EMI Details
  emiAmount: {
    type: Number,
    required: true,
    min: 0
  },
  emiSchedule: [{
    month: {
      type: Number, // 1-12
      required: true,
      min: 1,
      max: 12
    },
    year: {
      type: Number,
      required: true
    },
    dueDate: {
      type: Date,
      required: true
    },
    status: {
      type: String,
      enum: ['pending', 'processing', 'completed', 'failed', 'overdue'],
      default: 'pending'
    },
    paidAt: Date,
    paymentId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Payment',
      default: null
    },
    penaltyAmount: {
      type: Number,
      default: 0,
      min: 0
    }
  }],

  // Documents
  documents: [{
    type: {
      type: String, // 'identity', 'income', 'bank_statement', 'contract', 'other'
      required: true
    },
    url: {
      type: String,
      required: true
    },
    uploadedAt: {
      type: Date,
      default: Date.now
    }
  }],

  // Eligibility Check
  eligibilityCheck: {
    passed: {
      type: Boolean,
      default: false
    },
    creditScore: Number,
    incomeVerified: {
      type: Boolean,
      default: false
    },
    employmentVerified: {
      type: Boolean,
      default: false
    },
    eligibilityScore: Number, // 0-100
    checkedAt: Date
  },

  // Approval/Rejection
  approvedAt: Date,
  approvedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },
  rejectionReason: String,
  rejectedAt: Date,
  rejectedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    default: null
  },

  // Disbursement
  disbursedAt: Date,
  disbursedAmount: Number,
  disbursementReference: String,

  // Repayment
  totalPaid: {
    type: Number,
    default: 0,
    min: 0
  },
  totalRemaining: {
    type: Number,
    min: 0
  },
  repaidAt: Date,

  // Default
  defaultedAt: Date,
  defaultReason: String,

  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, {
  timestamps: true
});

// Indexes
rentalLoanSchema.index({ userId: 1, status: 1 });
rentalLoanSchema.index({ contractId: 1 });
rentalLoanSchema.index({ status: 1, createdAt: -1 });
rentalLoanSchema.index({ 'emiSchedule.dueDate': 1, 'emiSchedule.status': 1 }); // For overdue EMI tracking

// Generate loanId before saving
rentalLoanSchema.pre('save', async function (next) {
  if (!this.loanId) {
    const timestamp = Date.now();
    const random = Math.random().toString(36).substring(2, 9).toUpperCase();
    this.loanId = `LOAN-${timestamp}-${random}`;
  }

  // Calculate total remaining based on unpaid EMIs
  if (this.emiSchedule && this.emiSchedule.length > 0) {
    this.totalRemaining = this.emiSchedule.reduce((sum, emi) => {
      // If completed, don't count towards remaining
      if (emi.status === 'completed') return sum;
      // Sum up EMI amount + any penalties
      return sum + (this.emiAmount || 0) + (emi.penaltyAmount || 0);
    }, 0);
  } else if (this.loanAmount && this.totalPaid !== undefined) {
    // Fallback if schedule not generated yet (e.g. initial creation)
    // Estimate total payable as EMI * Tenure if available, else Loan Amount
    const totalPayable = (this.emiAmount && this.tenure) ? (this.emiAmount * this.tenure) : this.loanAmount;
    this.totalRemaining = Math.max(0, totalPayable - this.totalPaid);
  }

  this.updatedAt = Date.now();
  next();
});

// Generate EMI schedule
rentalLoanSchema.methods.generateEMISchedule = function () {
  const schedule = [];
  const startDate = new Date();
  const monthlyRate = this.interestRate / 100 / 12;
  const months = this.tenure;

  // Calculate EMI using formula: EMI = P × r × (1 + r)^n / ((1 + r)^n - 1)
  const emi = (this.loanAmount * monthlyRate * Math.pow(1 + monthlyRate, months)) /
    (Math.pow(1 + monthlyRate, months) - 1);

  this.emiAmount = Math.round(emi);

  for (let i = 0; i < months; i++) {
    const dueDate = new Date(startDate);
    dueDate.setMonth(dueDate.getMonth() + i + 1);

    const month = dueDate.getMonth() + 1;
    const year = dueDate.getFullYear();

    schedule.push({
      month: month,
      year: year,
      dueDate: dueDate,
      status: 'pending',
      penaltyAmount: 0
    });
  }

  this.emiSchedule = schedule;
};

// Virtual for overdue EMIs
rentalLoanSchema.virtual('overdueEMIs').get(function () {
  const now = new Date();
  return this.emiSchedule.filter(emi =>
    (emi.status === 'pending' || emi.status === 'overdue') &&
    new Date(emi.dueDate) < now
  );
});

// Virtual for next EMI due
rentalLoanSchema.virtual('nextEMIDue').get(function () {
  const now = new Date();
  const upcoming = this.emiSchedule.filter(emi =>
    emi.status === 'pending' &&
    new Date(emi.dueDate) >= now
  );
  return upcoming.length > 0 ? upcoming[0] : null;
});

// Method to refresh overdue status and calculate penalties
rentalLoanSchema.methods.refreshOverdueStatus = async function () {
  const now = new Date();
  now.setHours(0, 0, 0, 0);
  let modified = false;

  // Populate contract if not already populated to get late fee percentage
  if (!this.populated('contractId') && !this.contractId.lateFeePercentage) {
    await this.populate('contractId', 'lateFeePercentage');
  }

  const lateFeeRate = (this.contractId?.lateFeePercentage || 5) / 100;

  for (const emi of this.emiSchedule) {
    if (emi.status === 'completed') continue;

    const dueDate = new Date(emi.dueDate);
    dueDate.setHours(0, 0, 0, 0);

    if (dueDate < now) {
      // EMI is overdue
      if (emi.status !== 'overdue') {
        emi.status = 'overdue';
        modified = true;
      }

      // Calculate penalty: simple monthly penalty
      const diffTime = now.getTime() - dueDate.getTime();
      const overdueDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));
      const overdueMonths = Math.floor(overdueDays / 30) + 1;
      const newPenalty = Math.round(this.emiAmount * lateFeeRate * overdueMonths);

      if (emi.penaltyAmount !== newPenalty) {
        emi.penaltyAmount = newPenalty;
        modified = true;
      }
    }
  }

  // Update loan status to 'defaulted' if more than 3 EMIs are overdue
  const overdueCount = this.emiSchedule.filter(emi => emi.status === 'overdue').length;
  if (overdueCount >= 3 && this.status !== 'defaulted') {
    this.status = 'defaulted';
    this.defaultedAt = new Date();
    this.defaultReason = 'Multiple overdue EMI payments';
    modified = true;
  }

  if (modified) {
    this.updatedAt = new Date();
  }

  return modified;
};

// Method to calculate total outstanding
rentalLoanSchema.methods.getTotalOutstanding = function () {
  return this.emiSchedule.reduce((sum, emi) => {
    if (emi.status === 'completed') return sum;
    return sum + this.emiAmount + (emi.penaltyAmount || 0);
  }, 0);
};

const RentalLoan = mongoose.model("RentalLoan", rentalLoanSchema);

export default RentalLoan;

